### ISSUE TITLE
master does not build with lts-5.11

### ISSUE THREAD

**Issue by feuerbach** [simonmichael/hledger#335]
stack.yaml says:

```
# this or a newer snapshot is suggested
#resolver: lts-5.11
```

However, I tried building current master with lts-5.11 and got a bunch of errors like

```
    /home/feuerbach/source/hledger/hledger-api/hledger-api.hs:66:10: Not in scope: ‘title’
    
    /home/feuerbach/source/hledger/hledger-api/hledger-api.hs:67:10: Not in scope: ‘version’
    
    /home/feuerbach/source/hledger/hledger-api/hledger-api.hs:69:10:
        Not in scope: ‘license’
        Perhaps you meant data constructor ‘License’ (imported from Data.Swagger)
    
    /home/feuerbach/source/hledger/hledger-api/hledger-api.hs:153:60: Not in scope: ‘defaultOptions’
```

It would be good either to bump the lts version, or remove the recommendation altogether.

**Comment by simonmichael** [comment]
I've removed the misleading comment, which was just to remind me how to reference an LTS version. Thanks for the report.
