### ISSUE TITLE
Support for ghc-9.2

### ISSUE THREAD

**Issue by peti** [simonmichael/hledger#1774]
Is there any particular reason why `hlebger-lib` et all exclude base 4.16.0.0 as shipped with ghc-9.2.1? As far as I can tell, there's no problem building hleder-lib with the latest base.

There *are* problems building with `time-1.11.1.1`, however, which is not excluded by the constraints. The errors I see are:

~~~~
Hledger/Read/JournalReader.hs:717:20: error:
    Ambiguous occurrence ‘Year’
    It could refer to
       either ‘Data.Time.Calendar.Year’,
              imported from ‘Data.Time.Calendar’ at Hledger/Read/JournalReader.hs:89:1-25
              (and originally defined in ‘time-1.11.1.1:Data.Time.Calendar.Types’)
           or ‘Hledger.Data.Year’,
              imported from ‘Hledger.Data’ at Hledger/Read/JournalReader.hs:99:1-19
              (and originally defined in ‘Hledger.Data.Types’
                 at Hledger/Data/Types.hs:81:1-19)
~~~~

**Comment by simonmichael** [comment]
Thanks for the reminder. GHC 9.2.1 is officially released and it's certainly time we supported it.

**Comment by simonmichael** [comment]
hledger-lib in master builds with GHC 9.2.1 now. I have not tested other packages as their deps aren't ready yet, eg https://github.com/yesodweb/shakespeare/issues/261.

**Comment by simonmichael** [comment]
Update: on arm machines, ghc 9.2.1 is broken with respect to unicode, and can't compile some packages (like base-compat).

**Comment by simonmichael** [comment]
Update: ghc 9.2.2 is now looking pretty good, as far as I know. It is in stackage nightly, hledger and hledger-ui build cleanly, and we are waiting on yesod and like https://github.com/simonmichael/hledger/pull/1834 for hledger-web. Once that works, I might make 9.2 the default for development. It has the great advantage of running much better on mac m1 (almost 3x quicker than 9.0), and hopefully is a bit quicker on other machines as well.

**Comment by simonmichael** [comment]
At last: all hledger packages build with GHC 9.2.2 and it is the default version for development.
