### ISSUE TITLE
hledger-api doesn't build with swagger2 2.1.5

### ISSUE THREAD

**Issue by felixonmars** [simonmichael/hledger#612]
```
[1 of 1] Compiling Main             ( hledger-api.hs, dist/build/hledger-api/hledger-api-tmp/Main.dyn_o )

hledger-api.hs:220:10: error:
    • Cannot derive Generic-based Swagger Schema for Price
      Price is a mixed sum type (has both unit and non-unit constructors).
      Swagger does not have a good representation for these types.
      Use genericDeclareNamedSchemaUnrestricted if you want to derive schema
      that matches aeson's Generic-based toJSON,
      but that's not supported by some Swagger tools.
    • In the expression:
        Data.Swagger.Internal.Schema.$dmdeclareNamedSchema @Price
      In an equation for ‘declareNamedSchema’:
          declareNamedSchema
            = Data.Swagger.Internal.Schema.$dmdeclareNamedSchema @Price
      In the instance declaration for ‘ToSchema Price’
    |
220 | instance ToSchema Price
    |          ^^^^^^^^^^^^^^
```

**Comment by simonmichael** [comment]
Thanks, what GHC version is this ?

**Comment by felixonmars** [comment]
It's GHC 8.2.1. It builds fine with swagger2 2.1.4.1.

**Comment by simonmichael** [comment]
Oh right I get you. Thanks.

**Comment by simonmichael** [comment]
PS we do still need a to fix this for swagger 2.1.5 in the future, help welcome.

**Comment by simonmichael** [comment]
cf https://github.com/fpco/stackage/issues/2861

**Comment by fizruk** [comment]
@simonmichael the error message was designed to guide migration process.

```
    • Cannot derive Generic-based Swagger Schema for Price
      Price is a mixed sum type (has both unit and non-unit constructors).
      Swagger does not have a good representation for these types.
      Use genericDeclareNamedSchemaUnrestricted if you want to derive schema
      that matches aeson's Generic-based toJSON,
      but that's not supported by some Swagger tools.
```

Specifically this part:

```
      Use genericDeclareNamedSchemaUnrestricted ...
```

So you just need this change:

```diff
- instance ToSchema Price
+ instance ToSchema Price where
+   declareNamedSchema = genericDeclareNamedSchemaUnrestricted defaultSchemaOptions
```

**Comment by simonmichael** [comment]
Noted, thank you!

**Comment by juhp** [comment]
2.1.6 is out

**Comment by simonmichael** [comment]
Reopening this as a reminder to follow through with https://github.com/GetShopTV/swagger2/issues/122 .

**Comment by simonmichael** [comment]
hledger-api got removed from stackage, remember to re-add it when 1.4 is released.
