### ISSUE TITLE
Failed to build with brick 0.47

### ISSUE THREAD

**Issue by felixonmars** [simonmichael/hledger#995]
With the update of brick 0.46 -> 0.47, the following build failure appears:

```
[11 of 14] Compiling Hledger.UI.Main  ( Hledger/UI/Main.hs, dist/build/hledger-ui/hledger-ui-tmp/Hledger/UI/Main.dyn_o )

Hledger/UI/Main.hs:237:16: error:
    • Couldn't match expected type ‘IO a0’
                  with actual type ‘s0 -> IO s0’
    • Probable cause: ‘customMain’ is applied to too few arguments
      In the second argument of ‘($)’, namely
        ‘customMain myVty (Just eventChan) brickapp ui’
      In a stmt of a 'do' block:
        void $ customMain myVty (Just eventChan) brickapp ui
      In the expression:
        do dbg1IO "fsnotify using polling ?" $ isPollingManager mgr
           files <- mapM (canonicalizePath . fst) $ jfiles j
           let directories = nub $ sort $ map takeDirectory files
           dbg1IO "files" files
           ....
    |
237 |         void $ customMain myVty (Just eventChan) brickapp ui
    |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Hledger/UI/Main.hs:237:27: error:
    • Couldn't match expected type ‘Graphics.Vty.Vty’
                  with actual type ‘IO Graphics.Vty.Vty’
    • In the first argument of ‘customMain’, namely ‘myVty’
      In the second argument of ‘($)’, namely
        ‘customMain myVty (Just eventChan) brickapp ui’
      In a stmt of a 'do' block:
        void $ customMain myVty (Just eventChan) brickapp ui
    |
237 |         void $ customMain myVty (Just eventChan) brickapp ui
    |                           ^^^^^

Hledger/UI/Main.hs:237:34: error:
    • Couldn't match expected type ‘IO Graphics.Vty.Vty’
                  with actual type ‘Maybe (BC.BChan AppEvent)’
    • In the second argument of ‘customMain’, namely ‘(Just eventChan)’
      In the second argument of ‘($)’, namely
        ‘customMain myVty (Just eventChan) brickapp ui’
      In a stmt of a 'do' block:
        void $ customMain myVty (Just eventChan) brickapp ui
    |
237 |         void $ customMain myVty (Just eventChan) brickapp ui
    |                                  ^^^^^^^^^^^^^^

Hledger/UI/Main.hs:237:50: error:
    • Couldn't match expected type ‘Maybe (BC.BChan e0)’
                  with actual type ‘App UIState AppEvent Name’
    • In the third argument of ‘customMain’, namely ‘brickapp’
      In the second argument of ‘($)’, namely
        ‘customMain myVty (Just eventChan) brickapp ui’
      In a stmt of a 'do' block:
        void $ customMain myVty (Just eventChan) brickapp ui
    |
237 |         void $ customMain myVty (Just eventChan) brickapp ui
    |                                                  ^^^^^^^^

Hledger/UI/Main.hs:237:59: error:
    • Couldn't match expected type ‘App s0 e0 n0’
                  with actual type ‘UIState’
    • In the fourth argument of ‘customMain’, namely ‘ui’
      In the second argument of ‘($)’, namely
        ‘customMain myVty (Just eventChan) brickapp ui’
      In a stmt of a 'do' block:
        void $ customMain myVty (Just eventChan) brickapp ui
    |
237 |         void $ customMain myVty (Just eventChan) brickapp ui
    |                                                           ^^
```

**Comment by peti** [comment]
The same issue breaks `hledger-ui` in Nixpgs, too: https://hydra.nixos.org/build/90963591.

**Comment by simonmichael** [comment]
I've release hledger-ui-1.14.1 which should resolve this.

**Comment by simonmichael** [comment]
And now hledger-ui-1.14.2.
